---

root: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 6
  sourceType: "module"
  ecmaFeatures:
    jsx: true

plugins: ["@typescript-eslint", "react", "react-hooks", "jest", "testing-library"]

env:
  es6: true
  browser: true
  node: true
  jest: true
  jest/globals: true

extends:
  [
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:jest/recommended",
    "plugin:react/recommended",
    "plugin:react-hooks/recommended",
  ]

settings:
  react:
    version: "detect"

rules:
  quotes: ["error", "double"]
  "react/prop-types": 0
  "@typescript-eslint/explicit-module-boundary-types": 0

ignorePatterns: ["next.config.js"]
